version: '3.8'

services:
  web:
    build: .
    container_name: web_app
    depends_on:
      - postgres
      - mongo
      - rabbitmq
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}:/app
    env_file:
      - .env
    restart: always
    command:
      - "python"
      - "manage.py"
      - "runserver"
      - "0.0.0.0:8000"

  postgres:
    image: postgres:latest
    container_name: postgres_db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: mydatabase
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data:
